# This PersistentVolume statically provisions an EFS volume using the AWS EFS CSI driver
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  capacity:
    storage: 5Gi                # <--- Change this if you need a different size
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: ""          # <--- Keep empty for static provisioning
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-038d717155e5b652b   # <--- Change this to your actual EFS FileSystem ID
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi              # <--- Change this if you need a different size
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: efs-static-demo    # <--- Change label if needed
    project: roboshop           # <--- Change label if needed
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html   # <--- Change this if your app needs a different mount path
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-static
---
apiVersion: v1
kind: Service
metadata:
  name: efs-static
  labels:
    purpose: efs-static-demo    # <--- Change label if needed
    project: roboshop           # <--- Change label if needed
spec:
  type: LoadBalancer            # <--- Change to ClusterIP or NodePort if you don't want external access
  selector:
    purpose: efs-static-demo    # <--- Ensure this matches Pod labels
    project: roboshop           # <--- Ensure this matches Pod labels
  ports:
    - protocol: TCP
      port: 80                  # <--- Change if you want a different service port
      targetPort: 80            # <--- Change if your container listens on a different port
