apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    -  ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-038d717155e5b652b


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
    -  ReadWriteMany
  storageClassName: ""  # Match the PV for static provisioning
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-nginx
  labels:
    env: test
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: efs-svc
  labels:
    env: test
    project: roboshop
spec:
  type: LoadBalancer
  selector:
    env: test
    project: roboshop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80