apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  labels:
    project: roboshop
    component: catalogue
    tier: apps  



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    tier: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: catalogue
      tier: database
  template:
    metadata:
      name: catalogue
      labels:
        project: roboshop
        component: catalogue
        tier: app
    spec:
      containers:
      - name: catalogue
        image: joindevops/catalogue:v1
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    tier: app
spec:
  selector:
    project: roboshop
    component: catalogue
    tier: app  
  ports: 
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port



  