# ConfigMap: Stores environment variables for the shipping microservice
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app 
# Data section contains key-value pairs used by the app
data:
  CART_ENDPOINT: "cart:8080"  # Endpoint for cart service
  DB_HOST: "mysql"   # Hostname for MySQL database
---
# Deployment: Creates and manages pods for the shipping microservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  replicas: 1  # Number of pod copies
  selector:
    matchLabels:
      component: shipping
      project: roboshop
      tier: app  
  template:
    metadata:
      name: shipping
      labels:
        component: shipping
        project: roboshop
        tier: app  
    spec:
      containers:
      - name: shipping
        image: joindevops/shipping:v1  # Docker image for the app
        envFrom:
        - configMapRef:
            name: shipping  # Load environment variables from ConfigMap
---
# Service: Exposes the shipping pods inside the cluster
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  selector:
    component: shipping
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 # Port exposed by the service
    targetPort: 8080 # Port on the pod/container
