apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv
spec:
  storageClassName: "" # <-- match PVC
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-03ea32d59c92960b2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: "" # must match PV
  volumeName: ebs-static-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    project: roboshop
    env: dev
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: ebs-static-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ebs-static
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # changed from 8080
