# Pod: Example of a pod with multiple containers
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod  # Name of the pod
  annotations:
    purpose: demo of multi container  # Annotation for documentation
spec:
  containers:
  - name: nginx  # First container
    image: nginx:latest  # Nginx image
  - name: almalinux  # Second container
    image: almalinux:latest  # AlmaLinux image
    command: ["sleep","1000"]  # Command to keep container running
