apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  annotations:
    purpose: demo of multi container

spec:
  containers:
  - name: nginx
    image: nginx:latest
  - name: almalinux
    image: almalinux:latest
    cmd: ["sleep","1000"]
