apiVersion: v1
kind: Pod
metadata: 
  name: label-demo-pod
  labels:
    name: vs-vicky
    project: roboshop
    env: roboshop
    purpose: demo-for-labels
spec:
  containers:
  - name: nginx
    image: nginx:latest

