# Pod: Demonstrates resource requests and limits for containers
apiVersion: v1
kind: Pod
metadata:
  name: resources-demo      # Name of the pod
  labels:
    purpose: resources-demo  # Purpose label
spec:
  containers:
  - name: nginx  # Name of the container
    image: nginx  # Docker image for the container
    resources:
      requests:
        memory: "120Mi"  # Minimum memory required
        cpu: "150m"      # Minimum CPU required
      limits:
        memory: "150Mi"  # Maximum memory allowed
        cpu: "200m"      # Maximum CPU allowed
