apiVersion: v1
kind: Pod
metadata:
  name: env-demo
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: "join-devops"
    - name: join-month
      value: "march"