apiVersion: v1
kind: Pod
metadata:
  name: env demo
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: vsvicky
      value: "join-devops"
    - name: gss-elite-pg
      value: "march"