# Secret: Stores sensitive data for pods (base64 encoded)
apiVersion: v1
kind: Secret
metadata:
  name: pod-secrets  # Name of the Secret
# Type Opaque means generic secret
type: Opaque
# Data section contains base64 encoded values
data:
  username: dnN2aWNreQ==  # Username (base64)
  password: YXdz  # Password (base64)
