apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    env: development
    project: roboshop
    purpose: service-demo    
  ports:
    - protocol: TCP
      port: 80 # service
      targetPort: 80 # nginx
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: development
    project: roboshop
    purpose: service-demo
spec:
  containers:
  - name: nginx
    image: nginx


