apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    component: mysql
    project: roboshop
    environment: dev
spec:
  serviceName: mysql-headless
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: roboshop
      environment: dev
  template:
    metadata:
      name: mysql
      labels:
        component: mysql
        project: roboshop
        environment: dev
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        envFrom:
        - secretRef:
            name: mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: roboshop-ebs
      resources:
        requests:
          storage: 2Gi
spec:
  type: ClusterIP
  selector:
      component: mysql
      project: roboshop
      environment: dev        
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306 # conatiner port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    component: mysql
    project: roboshop
    environment: dev        
spec:
  serviceName: mysql-headless
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: roboshop
      environment: dev  
  template:
    metadata:
      name: mysql
      labels:
        component: mysql
        project: roboshop
        environment: dev
      conatiners:
      - name: mysql
        image: joindevops/mysql:v1
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        envFrom:
        - secretRef:
            name : mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: roboshop-ebs
      resources:
        requests:
          storage: 2Gi