apiVersion: apps/v1
kind: StatefulSet # Use StatefulSet for stateful apps like databases
metadata:
  name: mysql
  labels:
    component: mysql
    project: roboshop
    environment: dev
spec:
  serviceName: mysql-headless # Headless service required for StatefulSet
  replicas: 2 # Number of MySQL pods
  selector:
    matchLabels:
      component: mysql
      project: roboshop
      environment: dev
  template:
    metadata:
      name: mysql
      labels:
        component: mysql
        project: roboshop
        environment: dev
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1 # Custom MySQL image
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql # MySQL data directory
        envFrom:
        - secretRef:
            name: mysql # Inject MySQL root password from Secret
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ] # Only one node can use this volume at a time
      storageClassName: roboshop-ebs # Use EBS for dynamic storage
      resources:
        requests:
          storage: 2Gi # Each pod gets 2Gi storage
spec:
  type: ClusterIP
  selector:
      component: mysql
      project: roboshop
      tier: database        
  ports:
  - protocol: TCP
    port: 3306 # service port
    targetPort: 3306 # conatiner port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    component: mysql
    project: roboshop
    tier: database        
spec:
  serviceName: mysql-headless
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: roboshop
      tier: database  
  template:
    metadata:
      name: mysql
      labels:
        component: mysql
        project: roboshop
        tier: database
      conatiners:
      - name: mysql
        image: joindevops/mysql:v1
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        envFrom:
        - secretRef:
            name : mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: roboshop-ebs
      resources:
        requests:
          storage: 2Gi