apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-1
  labels:
    env: dev   # pod-affinity-2 will try to be near this pod
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-2
  labels:
    env: prod
    project: roboshop
spec:
  affinity:
    podAffinity:
       # Hard rule: must run near pods with env=dev
      # If no matching pod exists, pod-affinity-2 stays Pending
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector: 
          matchExpressions:
          - key: env
            operator: In
            values:
            - dev   # Target pods with this label
        topologyKey: topology.kubernetes.io/zone   # Try to schedule in the same zone
  containers:
  - name: nginx
    image: nginx

# Pod Affinity = pod wants to be near certain pods
# topologyKey = how "near" is measured (same node, zone, or region)
