apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-1
  labels:
    env: dev   # Pod-affinity-2 will try to be near this pod
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-2
  labels:
    env: prod
    project: roboshop
spec:
  affinity:
    podAffinity:
      # Soft rule: try to schedule near pods with env=dev
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100       # How strong the preference is (1-100)
        podAffinityTerm:
          labelSelector: 
            matchExpressions:
            - key: env
              operator: In
              values:
              - dev   # Target pods with this label
          topologyKey: topology.kubernetes.io/zone   # Try to schedule in the same zone
  containers:
  - name: nginx
    image: nginx
