apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    env: dev   # pod-2 will try to avoid running on the same node/zone as this pod
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    env: prod
    project: roboshop
spec:
  affinity:
    podAntiAffinity:
      # Hard rule: pod-2 must NOT run on the same zone as pods with env=dev
      # If no suitable node is available, pod-2 stays Pending
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector: 
          matchExpressions:
          - key: env
            operator: In
            values:
            - dev   # Target pods to avoid
        topologyKey: topology.kubernetes.io/zone   # Avoid pods in the same zone
  containers:
  - name: nginx
    image: nginx

# Pod Anti-Affinity = pod wants to stay away from certain pods
# topologyKey = how "far" is measured (same node, zone, or region)
# Hard rule = strict, pod waits if no suitable node is available
