apiVersion: v1
kind: Pod
metadata:
  name: node-selector
  labels:
    env: dev
    project: demo
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: Always  # Always pulls the image even if it exists locally
  nodeSelector:
    kubernetes.io/hostname: ip-192-168-44-84.ec2.internal  # Pod will only be scheduled on the node with this hostname
