apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod  
  labels:
    env: dev
    project: demo
spec: 
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
  nodeSelector:
     kubernetes.io/hostname: ip-192-168-44-84.ec2.internal  # Pod will only be scheduled on the node with this hostname
  tolerations:  # Allows pod to be scheduled on nodes with matching taints
  - key: "key"
    operator: "Equal"
    value: "value"
    effect: "NoSchedule"  # Added required effect field (options: NoSchedule, PreferNoSchedule, NoExecute)
