apiVersion: v1
kind: Pod
metadata:
  name: with-pod-anti-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - nodeSelectorTerms:
        - matchExpressions:
          - key: security
            operator: NotIn
            values:
            - vicky
  containers:
  - name: nginx
    image: nginx
