# Deployment: Creates and manages pods for the Redis database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  replicas: 1  # Number of pod copies
  selector:
    matchLabels:
      component: redis
      project: roboshop
      tier: database
  template:
    metadata:
      name: redis
      labels:
        component: redis
        project: roboshop
        tier: database
    spec:
      containers:
        - name: redis
          image: redis:7.0  # Docker image for Redis
---
# Service: Exposes the Redis pods inside the cluster
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    component: redis
    project: roboshop
    tier: database
spec:
  selector:
    component: redis
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 6379 # Port exposed by the service
    targetPort: 6379 # Redis standard port
