apiVersion: storage.k8s.io/v1
kind: StorageClass
reclaimPolicy: Retain
metadata:
  name: roboshop-efs
provisioner: efs.csi.aws.com
# parameters:
#   fileSystemId: fs-08969394d1bbe8f0d
#   provisioningMode: efs-ap
#   directoryPerms: "700"
#   gidRangeStart: "1000"
#   gidRangeEnd: "2000"
#   basePath: "/dynamic"