apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    env: dev
    project: roboshop
    tier: db
spec:
  replicas: {{ .Values.satatefulset.replicas }}
  selector: 
    matchLabels:
      env: dev
      project: roboshop
      tier: db
  template:
    metadata:
      labels:
        env: dev
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.satatefulset.imageUrl}}:{{ .Values.satatefulset.imageVersion}}
