apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    env: dev
    project: roboshop
    tier: db
spec:
  replicas: {{ .Values.statefulset.replicas }}
  selector: 
    matchLabels:
      env: dev
      project: roboshop
      tier: db
  template:
    metadata:
      labels:
        env: dev
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.statefulset.imageUrl }}:{{ .Values.statefulset.imageVersion }}
        volumeMounts:
          - name: mongodb-data
            mountPath: /data/db # MongoDB data directory
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ] # Only one node can use this volume at a time
      storageClassName: {{ .Values.statefulset.storage.storageClassName }} # Use EBS for dynamic storage
      resources:
        requests:
          storage: {{ .Values.statefulset.storage.size }} # Each pod gets 2Gi storage
          # Q: If we don't change volume space through Helm often, what's the use of the values.yml file?
          # A: Parameterizing values provides flexibility for:
          #    1. Environment-specific configs (dev=small, prod=large)
          #    2. Easy CLI overrides (--set statefulset.storage.size=5Gi)
          #    3. Future-proofing as application storage needs grow
          #    4. Documentation of configurable options
          #    5. CI/CD pipeline integration with dynamic values
          #    6. Testing with minimal resources