apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    env: dev
    project: roboshop
    tier: db
spec:
  replicas: {{ .Values.satatefulset.replicas }}
  selector: 
    matchLabels:
      env: dev
      project: roboshop
      tier: db
  template:
    metadata:
      labels:
        env: dev
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.satatefulset.imageUrl}}:{{ .Values.satatefulset.imageVersion}}
        volumeMounts:
          - name: mongodb-data
            mountPath: /data/db # MongoDB data directory
    volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: [ "ReadWriteOnce" ] # Only one node can use this volume at a time
        storageClassName: roboshop-ebs # Use EBS for dynamic storage
        resources:
          requests:
            storage: 2Gi # Each pod gets 2Gi storage