# ConfigMap: Stores environment variables for the user microservice
apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
# Data section contains key-value pairs used by the app
data:
  MONGO: "true"  # Enable MongoDB
  REDIS_URL: "redis://redis:6379"  # Redis connection string
  MONGO_URL: "mongodb://mongodb:27017/users"  # MongoDB connection string

---
# Deployment: Creates and manages pods for the user microservice
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
spec:
  replicas: 1  # Number of pod copies
  selector:
    matchLabels:
      component: user
      project: roboshop
      tier: app
  template:
    metadata:
      name: user
      labels:
        component: user
        project: roboshop
        tier: app
    spec: 
      containers:
      - name: user
        image: joindevops/user:v1  # Docker image for the app
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: user  # Load environment variables from ConfigMap
---
# Service: Exposes the user pods inside the cluster
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
spec:
  selector:
    component: user
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 # Port exposed by the service
    targetPort: 8080 # Port on the pod/container