apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    component: frontend
    project: roboshop
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend
      project: roboshop
      tier: web   

  template:
    metadata:
      name: frontend
      labels:
        component: frontend
        project: roboshop
        tier: web   
    spec:
      containers:
        - name: frontend
          image: joindevops/frontend:v1
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
  labels:
    component: frontend
    project: roboshop
    tier: web   
spec:
  selector:
    component: frontend
    project: roboshop
    tier: web   
  ports:
  - protocol: TCP
    port : 80
    targetPort: 8080 
