apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  # deployment labels
  labels:
    project: roboshop
    env: dev
    tier: database
spec:
  replicas: 1
   # These are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      project: roboshop
      env: dev
      tier: database
  # This is pod definition
  template:
    metadata:
      name: mongodb
      labels:
        project: roboshop
        env: dev
        tier: database
    spec:
      containers:
      - name: mongodb
        image: joindevops/mongodb:v1

---
 apiVersion: v1
 kind: Service
 metadata: 
  name: mongodb
  labels:
    project: roboshop
    env: dev
    tier: database
spec:
  selector:
    project: roboshop
    env: dev
    tier: database
  ports:
  - protocol: TCP
    port: 27017 #service port
    targetPort: 27017 # container
