# Deployment: Creates and manages pods for the MongoDB database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: database
spec:
  replicas: 1  # Number of pod copies
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: database
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: database
    spec:
      containers:
      - name: mongodb
        image: joindevops/mongodb:v1  # Docker image for MongoDB
---
# Service: Exposes the MongoDB pods inside the cluster
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: database
spec:
  type: ClusterIP  # Internal cluster service
  selector:
    project: roboshop
    component: mongodb
    tier: database
  ports:
  - protocol: TCP
    port: 27017 # Port exposed by the service
    targetPort: 27017 # Port on the pod/container
