apiVersion: v1
kind: Service
metadata:
 name: helm-service
 labels:
  env: dev
  project: roboshop
spec:
  type: LoadBalancer
  selector:
    env: dev
    project: roboshop
  ports:
   - port: 80
     targetPort: 80


