apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
  labels:
    component: payment
    project: roboshop
    tier: app
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"  

---
apiVersion: v1
kind: Secret
metadata:
  name: payment
  labels:
    component: payment
    project: roboshop
    tier: app
type: Opaque
data:
  AMQP_USER: "cm9ib3Nob3A="
  AMQP_PASS: "cm9ib3Nob3AxMjM="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    component: payment
    project: roboshop
    tier: app  
spec:
  replicas: 1
  selector:
    matchLabels:
      component: payment
      project: roboshop
      tier: app 
  template:
    metadata:
      name: payment
      labels:
        component: payment
        project: roboshop
        tier: app 
    spec:
      containers:
        - name: payment
          image: joindevops/payment:v1
          envFrom:
          - configMapRef:
              name: payment
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
  labels:
    component: payment
    project: roboshop
    tier: app 
spec:
  type: ClusterIP
  selector:
    component: payment
    project: roboshop
    tier: app 
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

