apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: roboshop
  labels:
    project: roboshop
    env: dev
    tier: db
spec:
  clusterIP: None
  selector:
    project: roboshop
    env: dev
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: {{ .Values.serviceHeadless.targetPort }}