apiVersion: v1
kind: ServiceAccount
metadata:
  name: roboshop-secret-reader
  namespace: roboshop
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::484907489214:role/SA-AWSSecretManager-Role
  labels:
    app.kubernetes.io/managed-by: eksctl

# you can done this as manually also there is no problem