apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
  namespace: roboshop
spec:
  serviceAccountName: roboshop-secret-reader
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: 
    - "/bin/bash"
    - "-c"
    - |
      # Retrieve secret and store in env variable
      SECRET=$(aws secretsmanager get-secret-value \
        --region us-east-1 \
        --secret-id roboshop/mysql/password \
        --query 'SecretString' \
        --output text)
      
      # Print success message (don't print actual secret in logs)
      echo "Secret successfully retrieved!"
      
      # Keep container running for debugging
      sleep 3600
  restartPolicy: Never
